BOARD_TAG = atmega328
ARDUINO_PORT = /dev/ttyUSB0
USER_LIB_PATH = /home/flugkatze/flugkatze/flugkatze_test/PID_class/lib
ARDUINO_LIBS = Wire
ARDUINO_LIBS += PID

include /usr/share/arduino/Arduino.mk

