BOARD_TAG = uno
# BOARD_TAG = atmega328
# BOARD_TAG = nano
ARDUINO_PORT = /dev/ttyUSB0
# ARDUINO_PORT = /dev/ttyACM0
USER_LIB_PATH = ../../lib
ARDUINO_LIBS = Wire
ARDUINO_LIBS += MPU6050
ARDUINO_LIBS += i2cdevlib/Arduino/I2Cdev
# ARDUINO_LIBS += ExponentialFilter2

include ../../lib/Arduino-Makefile/Arduino.mk

