BOARD_TAG = atmega328
ARDUINO_PORT = /dev/ttyUSB0
USER_LIB_PATH = ../../libs
ARDUINO_LIBS = Wire
ARDUINO_LIBS += MPU6050
ARDUINO_LIBS += i2cdevlib/Arduino/I2Cdev

include /usr/share/arduino/Arduino.mk

