ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = ../../lib/Arduino-Makefile
AVR_TOOLS_DIR = /usr

BOARD_TAG = nano
# BOARD_TAG = bluepill
BOARD_SUB = atmega328
# BOARD_SUB = generic_stm32f103c
ARDUINO_PORT = /dev/ttyUSB0
USER_LIB_PATH = ../../lib
ARDUINO_LIBS = Wire
ARDUINO_LIBS += MPU6050
ARDUINO_LIBS += i2cdevlib/Arduino/I2Cdev
ARDUINO_LIBS += ExponentialFilter2
ARDUINO_LIBS += BMP180

include ../../lib/Arduino-Makefile/Arduino.mk

