ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = ../../lib/Arduino-Makefile
AVR_TOOLS_DIR = /usr

BOARD_TAG = nano
BOARD_SUB = atmega328
ARDUINO_PORT = /dev/ttyUSB0
USER_LIB_PATH = ../../lib
ARDUINO_LIBS = Wire
ARDUINO_LIBS += MPU6050
ARDUINO_LIBS += i2cdevlib/Arduino/I2Cdev
ARDUINO_LIBS += ExponentialFilter2

include ../../lib/Arduino-Makefile/Arduino.mk

