BOARD_TAG = atmega328
ARDUINO_PORT = /dev/ttyUSB0
USER_LIB_PATH = /home/flugkatze/flugkatze/flugkatze_test/class_test/lib
ARDUINO_LIBS = Wire
ARDUINO_LIBS += Morse

include /usr/share/arduino/Arduino.mk

